# Generated by Django 5.2.12 on 2026-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_autor_categoria_editora_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
